spring:
  profiles: prod

  server:
    port: 8081

  data:
    elasticsearch:
      cluster-name: es-cluster
      cluster-nodes: 114.67.239.37:50005
#      properties:
      repositories:
        enabled: true
