spring:
  profiles: test

  server:
    port: 8082

  data:
    elasticsearch:
      cluster-name: es-cluster
      cluster-nodes: 114.67.239.37:50005
#      properties:
      repositories:
        enabled: true