spring:
  profiles: dev

  server:
    port: 8080

  data:
    elasticsearch:
      cluster-name: es-cluster
      cluster-nodes: 114.67.239.37:50005,114.67.239.37:50003
#      properties:
      repositories:
        enabled: true
